glew: Compile with -D_GNU_SOURCE
Required with glibc 2.26
when x11 is not in distro features it errors
out due to mising CLOCK_REALTIME

 error: 'CLOCK_REALTIME' undeclared (first use in this function);
did you mean '_XOPEN_REALTIME'?
    if (clock_gettime(CLOCK_REALTIME, &ts) == -1)
                      ^~~~~~~~~~~~~~
                      _XOPEN_REALTIME

(From OE-Core rev: 3a46984a68c423f4844879413d7c427dad4050e3)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>